apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nuagent
spec:
  selector:
    matchLabels:
      name: nuagent
  template:
    metadata:
      labels:
        name: nuagent
    spec:
      hostNetwork: true
      containers:
      - name: nuagent
        image: nubeva/nuagent
        imagePullPolicy: Always
        args: ["--accept-eula", "--nutoken", "lnveoaaj_qOQnT5Nt9eQax1JuAEJjdxl379uaqoqvqVeLgo1NNEavng7tvv5aJAAdEGj73Jto", "-noautoupdate"]
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_ADMIN", "SYS_PTRACE", "SYS_RESOURCE"]
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: vhost
            mountPath: /host
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /
          name: vhost
